#!/usr/bin/env bash
# Auto-populates docs/environments.md with the install/test environment and
# (optionally) a Playwright result row. Public-safe: no IPs/hostnames/tailnet.
#   scripts/record-env.sh [--with-tests]
set -euo pipefail
cd "$(dirname "$0")/.."

WITH_TESTS=0
[[ "${1:-}" == "--with-tests" ]] && WITH_TESTS=1

node_v=$(node --version 2>/dev/null || echo -)
next_v=$(node -p "require('$PWD/pwa/node_modules/next/package.json').version" 2>/dev/null || echo -)
py_v=$(python3 --version 2>/dev/null | cut -d' ' -f2 || echo -)
uv_v=$(uv --version 2>/dev/null | awk '{print $2}' || echo -)
docker_v=$(docker --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1 || echo -)
os=$(grep PRETTY_NAME /etc/os-release 2>/dev/null | cut -d'"' -f2 || uname -s)
kernel=$(uname -r)
cpu=$(grep -m1 'model name' /proc/cpuinfo 2>/dev/null | cut -d: -f2 | xargs || sysctl -n hw.model 2>/dev/null || echo -)
ram=$(free -h 2>/dev/null | awk '/Mem:/{print $2}' || sysctl -n hw.memsize 2>/dev/null || echo -)
svcs=$(systemctl --user is-active lk-pwa lk-agent opencode-serve 2>/dev/null | tr '\n' ' ' || echo -)
date_utc=$(date -u '+%Y-%m-%d %H:%M')

tests_col='skipped'
if [[ $WITH_TESTS -eq 1 ]]; then
  cd pwa
  if out=$(npx playwright test 2>&1 | tail -1); then tests_col="$out"; else tests_col="FAILED — $out"; fi
  cd ..
fi

if [[ $WITH_TESTS -eq 1 ]]; then
  cd pwa
  if out=$(npx playwright test 2>&1 | tail -1 | xargs); then tests_col="$out"; else tests_col="FAILED — $out"; fi
  cd ..
fi

doc=docs/environments.md
intro='# Environments — install & test record

Auto-generated by `scripts/record-env.sh` (`npm run verify`). Rows: newest first, capped at 15.
Private details (IPs, hostnames, ssh): `docs/local.md` — gitignored, never committed.

## Install target

One Linux box runs the whole server side (PWA, LiveKit, voice agent, opencode) via
docker compose + systemd **user** units; a Mac Studio serves local speech models (MLX)
over the LAN; the phone is just a browser (PWA) on the tailnet. Install: README.

## Test runs'

# rebuild: intro + header + separator + prior rows (newest first, max 15) + new row
{
  echo "$intro"
  echo '| date (UTC) | host | os / kernel | cpu / ram | stack (node, next, py, uv, docker) | services (pwa agent oc) | tests |'
  echo '|---|---|---|---|---|---|---|'
  { grep -E '^\| 20[0-9-]' "$doc" 2>/dev/null || true; } | head -14
  echo "| ${date_utc} | $(hostname -s) | ${os} / ${kernel} | ${cpu} / ${ram} | node ${node_v}, next ${next_v}, py ${py_v}, uv ${uv_v}, docker ${docker_v} | ${svcs} | ${tests_col} |"
} > "$doc.tmp"
mv "$doc.tmp" "$doc"

echo "recorded: ${tests_col}"
